<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>IPMan.Application</RootNamespace>
    <AssemblyName>IPMan.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPMan.Domain\IPMan.Domain.csproj" />
  </ItemGroup>
</Project>
